// Code generated by "stringer -type=accent -output=tokens_accent_auto.go -trimprefix=accent"; DO NOT EDIT.

package tokenizer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[accentNone-0]
	_ = x[accentAcute-1]
	_ = x[accentGrave-2]
	_ = x[accentCircumflex-3]
	_ = x[accentDieresis-4]
}

const _accent_name = "NoneAcuteGraveCircumflexDieresis"

var _accent_index = [...]uint8{0, 4, 9, 14, 24, 32}

func (i accent) String() string {
	if i < 0 || i >= accent(len(_accent_index)-1) {
		return "accent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _accent_name[_accent_index[i]:_accent_index[i+1]]
}
